services:
  mongo3:
    image: mongo:latest
    container_name: mongo3
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  chatapp-sample-gorilla:
    build: .
    depends_on:
      - mongo3
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo3:27017
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

volumes:
  mongo-data: